name: Generate GitHub Contribution Animation

on:
  # Executa automaticamente todos os dias à meia-noite UTC
  schedule:
    - cron: "0 0 * * *"

  # Permite execução manual via GitHub Actions
  workflow_dispatch:

  # Executa quando houver push na branch 'main'
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      # Clona o repositório para o ambiente de execução
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera a animação do gráfico de contribuições
      - name: Generate GitHub Contribution Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Verifica a geração correta dos arquivos SVG
      - name: Verify SVG files
        run: |
          for file in dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg; do
            if [ ! -f "$file" ]; then
              echo "Erro: $file não foi gerado corretamente."
              exit 1
            fi
          done

      # Publica os arquivos SVG na branch 'output'
      - name: Deploy SVG files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Notifica o status da execução do workflow
      - name: Notify workflow status
        if: always()
        run: |
          case "${{ job.status }}" in
            success) echo "🎉 Workflow executado com sucesso!";;
            failure) echo "❌ Workflow falhou. Verifique os logs para mais detalhes.";;
            *) echo "⚠️ Status do workflow: ${{ job.status }}";;
          esac
